remote_theme: tedivm/jekyll-theme-portfolio


title: Sameer Doshi's Page
author: Sameer Doshi
email: findme_on_linkedin@null.com
description: >
  Sameer Doshi. Sameer Chopra. Sameer Doshi Microsoft
  Author, Humorist, DevOps Enthusiast, Cloud Solutions Architect, Automation!


# Header Links - all optional. If set these create header links.
homepage: https://sdoshi.com
twitter_username: therealsameerc
github_username: sameerdoshi
linkedin_username: sameerdoshidevopsenthusiast


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # Lets us test remote themes locally.


avatar: https://sdoshi.blob.core.windows.net/pics/sameeranime.png